name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_IMAGE: tjjp/garage-pi-v3
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      DOCKER_TARGET_PLATFORM: linux/arm/v6
      
    steps:
    - name: Docker Login      
      if: success()      
      run: |        
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin

    - name: Checkout the code       
      uses: actions/checkout@v3 
      
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest 
  
    - name: Run Buildx (push image)
      if: success()      
      run: |        
        docker buildx build --platform ${DOCKER_TARGET_PLATFORM} --file ./Dockerfile --tag ${DOCKER_IMAGE}:$(date +%s) --output type=image,push=true .
